### ISSUE TITLE
doesn't work with latest tmux

### ISSUE THREAD

**Issue by sandrodz** [ConradIrwin/vim-bracketed-paste#32]
Plugin works fine outside tmux, but within tmux same old indentation hell breaks loose.

Any ideas how to fix this?

**Comment by fabienduhamel** [comment]
Same issue here.

**Comment by ConradIrwin** [comment]
We've added and removed tmux specific code a couple of times now — I don't use tmux, and it sounds like it has very complicated handling of terminal escapes (unsurprisingly!). I'd be very happy for anyone to pick this up and figure out exactly what the problem is, but please see also #28 #18 #14  #21 #23 and #25.

**Comment by fabienduhamel** [comment]
Thanks for the reply. None of these links gives me a working solution. I'm currently trying to fix it by myself.

**Comment by fabienduhamel** [comment]
I'm bored of tmux general issues for a couple of days, I deleted it.

**Comment by ConradIrwin** [comment]
😃Sent via SuperhumanOn Thu, Jun 01, 2017 at 3:15 PM, Fabien Duhamel<notifications@github.com>wrote:I'm bored of tmux general issues for a couple of days, I deleted it.

**Comment by amosbird** [comment]
Just hitted by this. Hope someone can share a solution.

**Comment by amosbird** [comment]
Just remove all the tmux wraping stuff and it's done. Thanks @nicm !

**Comment by sandrodz** [comment]
@amosbird how did you fix it?

**Comment by nicm** [comment]
If you remove the DCS wrapping it should work in any tmux since https://github.com/tmux/tmux/commit/f4fdddc9306886e3ab5257f40003f6db83ac926b

**Comment by ryanpcmcquen** [comment]
@nicm you should PR that.

**Comment by von** [comment]
@nicm I think you are talking about a solution that works with 'tmux paste-buffer -p' as opposed to pasting from the system paste buffer with Command-V?

**Comment by nicm** [comment]
No, it is supported for both.


On 11 Jun 2017 7:03 pm, "Von Welch" <notifications@github.com> wrote:

@nicm <https://github.com/nicm> I think you are talking about a solution
that works with 'tmux paste-buffer -p' as opposed to pasting from the
system paste buffer with Command-V?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ConradIrwin/vim-bracketed-paste/issues/32#issuecomment-307646009>,
or mute the thread

**Comment by von** [comment]
Thanks for clarifying. Like others on this thread, something recently broke indentation pasting from the system pastebuffer into vim running in tmux for me and removing the wrapping (i.e. making `WrapForTmux()` a no-op) doesn't help.

**Comment by nicm** [comment]
Show me what you have in your script now.

**Comment by von** [comment]
Here you go: https://github.com/von-forks/vim-bracketed-paste/blob/master/plugin/bracketed-paste.vim

As far as I can tell, `XTermPasteBegin()` is never invoked as I don't see the message from the echom I added for debugging.

**Comment by nicm** [comment]
Looks OK to me. What tmux version? If it is not 2.5 or master then please
upgrade and make sure the  problem still exists. If it does, can you please
do

tmux -Ltest -f/dev/null -vvvv new

Then run vim, paste something short, then exit vim and tmux and show me the
tmux-server*.log file from the current working directory.

**Comment by von** [comment]
I am running tmux 2.5 installed via homebrew.

And I've noticed my problem comes and goes depending on how I start vim. If I start vim with a file on the command line or loading a session, pasting and indentation is broken. If I start vim without any commandline arguments and then open a file, pasting works without indentation as desired. So I've got some startup weirdness going on and will go debug on my own for a bit. Thanks for your help.

**Comment by von** [comment]
If I change from setting `t_ti` and `t_te` to setting `t_SI` and `t_EI`, i.e., I revert fd01b5d333b9aa190af4ea718280c54bcbb71070, everything works perfectly. Using `t_ti` and `t_te` work for me, but seemingly only after running a curses based program from within vim (vifm, which is how I normally open a file).

For clarity, this fixes things for me:
> -let &t_ti .= "\<Esc>[?2004h"
> -let &t_te .= "\<Esc>[?2004l"
> +let &t_SI .= "\<Esc>[?2004h"
> +let &t_EI .= "\<Esc>[?2004l"

According to `:help` `t_ti` and `t_te` are about entering and leaving "termcap" mode and `t_SI` and `t_EI` are entering and leaving "insert" mode.  I don't understand why bracketed-paste changed - the comment on the above commit doesn't make sense to me - and I'm hoping this gives someone who understand that change a clue as to why it's not working well for me.

Since it might be relevant, I'm running vim 8.0 (patches 1-636), in tmux 2.5, in iTerm 3.0.15. (And this is all with the tmux wrapping removed per #33.)

**Comment by von** [comment]
OK, reading fd01b5d333b9aa190af4ea718280c54bcbb71070 more carefully, I understand it is about making pasting work from normal and visual mode and sure enough, I confirmed that using `t_SI` and `t_EI` instead of `t_ti` and `t_te` breaks pasting from normal and visual mode. I tried setting all four, and that doesn't seem to help.

**Comment by ssiegel** [comment]
Vim seems to include support for bracketed paste as of 8.0.0210. Maybe there is some interference that is masked by signalling bracketed paste support on every change to insert mode? Unfortunately I am not able to investigate that right now.

**Comment by v** [comment]
@nicm original suggestion worked for me

This diff works for me on Mac OSX with tmux 2.5 and vim 7.4
```diff
diff --git a/plugin/bracketed-paste.vim b/plugin/bracketed-paste.vim
index 196ec9b..17c688f 100644
--- a/plugin/bracketed-paste.vim
+++ b/plugin/bracketed-paste.vim
@@ -24,8 +24,8 @@ function! WrapForTmux(s)
   return tmux_start . substitute(a:s, "\<Esc>", "\<Esc>\<Esc>", 'g') . tmux_end
 endfunction
 
-let &t_ti .= WrapForTmux("\<Esc>[?2004h")
-let &t_te .= WrapForTmux("\<Esc>[?2004l")
+let &t_ti .= "\<Esc>[?2004h"
+let &t_te .= "\<Esc>[?2004l"
 
 function! XTermPasteBegin(ret)
   set pastetoggle=<f29>

```

**Comment by ConradIrwin** [comment]
Ok. I've gone with @v's solution.

Looking forward to new reports of "doesn't work in tmux" :D.

**Comment by chrisjohnson** [comment]
I can confirm that this doesn't work in tmux, and since vim 8 ships support natively, the only real point of a plugin here is to wrap for tmux.

Maybe worth updating the README to specify that this is for 7.x since it doesn't serve any purpose in 8.x

**Comment by chrisjohnson** [comment]
Also fwiw this bit of config that I similarly lifted from that SO article actually does make bracketed paste mode work inside of tmux... not sure what that means. If you are not keen on supporting tmux in your plugin and just want to serve 7.x users I'm fine taking my config and wrapping it up into a different plugin

**Comment by ryanpcmcquen** [comment]
I've rolled my own plugin also: https://github.com/ryanpcmcquen/fix-vim-pasting
